### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by ecreatures** [letchepare/CryptoCaptcha#1]
Il faudrait pouvoir avoir le Captcha qui prend en compte la langue de l'utilisateur. Pour faire ca, il suffit d'ajouter la var de lang SPIP #LANG à l'url de l'API apellée.
`<script src="https://www.google.com/recaptcha/api.js?hl=#LANG" async defer></script>`

**Comment by letchepare** [comment]
Issue résolu par le commit #2
